### ISSUE TITLE
Add AllTheGate Credit Card Information on Admin Configuration.

### ISSUE THREAD

**Issue by thruthesky** [thruthesky/english#189]
1. [Charles] Add field for AllTheGate Information.
    * Need add a text input box to save AllTheGate id.
    * And change the 'incharge' to mr. song.

 2. [Mr. Song] will update AGS_pay.php.
   * Since the ags id is saved in meta, you need to get it from meta.

 3. [mr. song] will update mall url.

**Comment by lancelynyrd** [comment]
done adding AllTheGate Credit Card Option on admin config.
